export const PRODUCTS = [
  {
    id: 'umivalica',
    nameSr: 'Umivalica za čišćenje lica',
    nameEn: 'Face Cleanser',
    descriptionSr: 'Prirodna umivalica obogaćena hijaluronskim gelom, ekstraktom zelenog čaja i hidrolat matičnjaka. Skida šminku bez osećaja zatezanja.',
    descriptionEn: 'Natural face wash enriched with hyaluronic gel, green tea extract and lemon balm hydrolate. Removes makeup without tightness.',
    ingredients: ['Hijaluronski gel', 'Ekstrakt zelenog čaja', 'Hidrolat matičnjaka'],
    ingredientsEn: ['Hyaluronic gel', 'Green tea extract', 'Lemon balm hydrolate'],
    url: 'https://beescare.rs/proizvodi/umivalica-za-ciscenje-lica/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2025/08/Umivalica-product-fotografija-600x600.jpg',
    concerns: ['cleansing', 'sensitive', 'daily', 'makeup removal'],
    category: 'face'
  },
  {
    id: 'hidratantna-krema',
    nameSr: 'Hidratantna krema za lice',
    nameEn: 'Moisturizing Face Cream',
    descriptionSr: 'Sa aloja vera gelom i bakučijem. Vitamini A, C, E i pčelinji vosak koji stvara zaštitnu barijeru na koži.',
    descriptionEn: 'With aloe vera gel and bakuchi oil. Vitamins A, C, E and beeswax that creates a protective skin barrier.',
    ingredients: ['Aloja vera gel', 'Bakuči ulje', 'Pčelinji vosak', 'Vitamin E'],
    ingredientsEn: ['Aloe vera gel', 'Bakuchi oil', 'Beeswax', 'Vitamin E'],
    url: 'https://beescare.rs/proizvodi/hidratantna-krema/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2021/08/Hidratantna-Krema-Tuba-600x600.jpg',
    concerns: ['dry', 'dehydration', 'sensitive', 'daily moisturizing', 'barrier'],
    category: 'face'
  },
  {
    id: 'antirid-krema',
    nameSr: 'Vitaminska antirid krema',
    nameEn: 'Anti-Wrinkle Vitamin Cream',
    descriptionSr: 'Noćna krema sa smiljem, šea puterom i uljem kantariona. Smanjuje bore, fleke i znake starenja.',
    descriptionEn: 'Night cream with immortelle, shea butter and St. John\'s wort oil. Reduces wrinkles, spots and signs of aging.',
    ingredients: ['Smilje (helichrysum)', 'Šea puter', 'Ulje kantariona', 'Vitamin E'],
    ingredientsEn: ['Immortelle (helichrysum)', 'Shea butter', 'St. John\'s wort oil', 'Vitamin E'],
    url: 'https://beescare.rs/proizvodi/krema-protiv-bora/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2021/08/Vitaminska-Krema-Tuba-600x600.jpg',
    concerns: ['aging', 'wrinkles', 'pigmentation', 'spots', 'anti-aging'],
    category: 'face'
  },
  {
    id: 'melem-ekcem',
    nameSr: 'Melem za ekcem i psorijazu',
    nameEn: 'Eczema & Psoriasis Balm',
    descriptionSr: 'Prva pomoć kod ekcema, psorijaze i dermatitisa. Antibakterijsko i protivupalno dejstvo. Efikasnost potvrđena kod 10.000+ korisnika.',
    descriptionEn: 'First aid for eczema, psoriasis and dermatitis. Antibacterial and anti-inflammatory. Effectiveness confirmed by 10,000+ users.',
    ingredients: ['Nevena', 'Kantarion', 'Bokvica', 'Eterično ulje čajevca', 'Šea puter'],
    ingredientsEn: ['Calendula', 'St. John\'s wort', 'Plantain', 'Tea tree oil', 'Shea butter'],
    url: 'https://beescare.rs/proizvodi/melem-za-ekcem/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2025/03/Melem-Ekcem-Prirodni-2-600x600.jpg',
    concerns: ['eczema', 'psoriasis', 'dermatitis', 'rash', 'itching', 'inflammation'],
    category: 'treatment'
  },
  {
    id: 'melem-obnova',
    nameSr: 'Melem za obnovu kože',
    nameEn: 'Skin Renewal Balm',
    descriptionSr: 'Za opekotine, ispucale pete, posekotine i herpes. Antiseptičko, antibakterijsko i protivupalno dejstvo.',
    descriptionEn: 'For burns, cracked heels, cuts and cold sores. Antiseptic, antibacterial and anti-inflammatory properties.',
    ingredients: ['Nevena', 'Kamilica', 'Bokvica', 'Eterično ulje čajevca', 'Kakao puter'],
    ingredientsEn: ['Calendula', 'Chamomile', 'Plantain', 'Tea tree oil', 'Cocoa butter'],
    url: 'https://beescare.rs/proizvodi/melem-za-opekotine/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2025/03/Melem-Obnova-Prirodni-1.jpg',
    concerns: ['burns', 'cracked heels', 'cuts', 'cold sores', 'damaged skin'],
    category: 'treatment'
  },
  {
    id: 'balzam-usne',
    nameSr: 'Prirodni balzam za usne',
    nameEn: 'Natural Lip Balm',
    descriptionSr: 'Leči ispucale usne, miriše na kakao. Ne ostavlja boju, pogodan za sve. Ne izaziva zavisnost.',
    descriptionEn: 'Heals chapped lips, smells like cocoa. Leaves no color, suitable for everyone. Does not cause dependency.',
    ingredients: ['Pčelinji vosak', 'Kakao puter', 'Šea puter'],
    ingredientsEn: ['Beeswax', 'Cocoa butter', 'Shea butter'],
    url: 'https://beescare.rs/proizvodi/prirodni-balzam-za-usne/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2021/07/Zensko-labelo-prirodno.jpg.webp',
    concerns: ['chapped lips', 'dry lips', 'lip care'],
    category: 'treatment'
  },
  {
    id: 'puter-kokos',
    nameSr: 'Puter za telo — Kokos',
    nameEn: 'Body Butter — Coconut',
    descriptionSr: 'Duboka hidratacija tela. Avokado puter i bademovo ulje za elastičnost. Pomaže sa strijama. Miriše na kokos.',
    descriptionEn: 'Deep body hydration. Avocado butter and almond oil for elasticity. Helps with stretch marks. Coconut scent.',
    ingredients: ['Avokado puter', 'Bademovo ulje', 'Kokosovo ulje', 'Pčelinji vosak'],
    ingredientsEn: ['Avocado butter', 'Almond oil', 'Coconut oil', 'Beeswax'],
    url: 'https://beescare.rs/proizvodi/puter-za-telo-kokos/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2023/04/Puter-za-telo-kokos.jpg.webp',
    concerns: ['dry body', 'stretch marks', 'body hydration', 'post-sun'],
    category: 'body'
  },
  {
    id: 'puter-pomorandza',
    nameSr: 'Puter za telo — Pomorandža',
    nameEn: 'Body Butter — Orange',
    descriptionSr: 'Ista formula kao kokos verzija, miris pomorandže. Duboka hidratacija i elastičnost kože tela.',
    descriptionEn: 'Same formula as coconut version, orange scent. Deep hydration and skin elasticity.',
    ingredients: ['Avokado puter', 'Bademovo ulje', 'Kokosovo ulje', 'Eterično ulje pomorandže'],
    ingredientsEn: ['Avocado butter', 'Almond oil', 'Coconut oil', 'Sweet orange essential oil'],
    url: 'https://beescare.rs/proizvodi/puter-za-telo-pomorandza/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2021/08/Puter-za-telo-pomorandza2.jpg.webp',
    concerns: ['dry body', 'stretch marks', 'body hydration'],
    category: 'body'
  },
  {
    id: 'piling-cokolada',
    nameSr: 'Piling za telo — Čokolada',
    nameEn: 'Body Scrub — Chocolate',
    descriptionSr: 'Prirodni šećerni piling. Uklanja mrtve ćelije, koža postaje glatka i mekana. Ulje kamilice i šea puter.',
    descriptionEn: 'Natural sugar scrub. Removes dead skin cells, skin becomes smooth and soft. Chamomile oil and shea butter.',
    ingredients: ['Šećer', 'Ulje kamilice', 'Šea puter', 'Vitamin E'],
    ingredientsEn: ['Sugar', 'Chamomile oil', 'Shea butter', 'Vitamin E'],
    url: 'https://beescare.rs/proizvodi/piling-za-telo-cokolada/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2024/07/Prirodni-piling-za-telo-body-scrub.jpg.webp',
    concerns: ['rough skin', 'exfoliation', 'dead skin', 'body texture'],
    category: 'body'
  },
  {
    id: 'krema-ruke',
    nameSr: 'Krema za ruke — Breskva',
    nameEn: 'Hand Cream — Peach',
    descriptionSr: 'Hidratacija i regeneracija ruku. Kamilica i neven smiruju iritaciju. Brzo se upija, ne ostavlja masnoću.',
    descriptionEn: 'Hand hydration and regeneration. Chamomile and calendula soothe irritation. Absorbs quickly, no greasy feel.',
    ingredients: ['Aloja vera', 'Ulje jojobe', 'Šea puter', 'Ulje koštica kupine'],
    ingredientsEn: ['Aloe vera', 'Jojoba oil', 'Shea butter', 'Blackberry seed oil'],
    url: 'https://beescare.rs/proizvodi/krema-za-ruke/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2025/01/KremaZaRuke-Breskva-600x600.jpg',
    concerns: ['dry hands', 'cracked hands', 'hand care', 'irritated hands'],
    category: 'body'
  },
  {
    id: 'dezodorans-mandarina',
    nameSr: 'Dezodorans — Mandarina',
    nameEn: 'Deodorant — Mandarin',
    descriptionSr: 'Prirodni dezodorans bez aluminijuma. Miris mandarine. Ne ostavlja tragove na odeći.',
    descriptionEn: 'Natural aluminum-free deodorant. Mandarin scent. Leaves no stains on clothes.',
    ingredients: ['Kokosovo ulje', 'Soda bikarbona', 'Makadamija ulje', 'Eterično ulje mandarine'],
    ingredientsEn: ['Coconut oil', 'Baking soda', 'Macadamia oil', 'Mandarin essential oil'],
    url: 'https://beescare.rs/proizvodi/prirodni-dezodorans-mandarina/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2023/03/dezodorans-mandarina-prirodni.jpg',
    concerns: ['deodorant', 'natural deodorant', 'aluminum-free', 'body odor'],
    category: 'body'
  },
  {
    id: 'dezodorans-bor',
    nameSr: 'Dezodorans — Iglice bora',
    nameEn: 'Deodorant — Pine',
    descriptionSr: 'Ista formula kao mandarina, miris iglica bora. Bez aluminijuma, bez tragova.',
    descriptionEn: 'Same formula as mandarin, pine needle scent. Aluminum-free, no stains.',
    ingredients: ['Kokosovo ulje', 'Soda bikarbona', 'Makadamija ulje', 'Eterično ulje bora'],
    ingredientsEn: ['Coconut oil', 'Baking soda', 'Macadamia oil', 'Pine essential oil'],
    url: 'https://beescare.rs/proizvodi/prirodni-dezodorans-iglice-bora/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2023/03/dezodorans-iglice-bora-prirodni.jpg',
    concerns: ['deodorant', 'natural deodorant', 'aluminum-free'],
    category: 'body'
  },
  {
    id: 'spf-krema',
    nameSr: 'Krema za sunčanje SPF 30',
    nameEn: 'Sunscreen SPF 30',
    descriptionSr: '100% prirodna krema za sunčanje. Ne ostavlja beli trag, vodootporna. Mineralni UV filteri koji blokiraju a ne apsorbuju zrake.',
    descriptionEn: '100% natural sunscreen. No white cast, water-resistant. Mineral UV filters that block rather than absorb rays.',
    ingredients: ['Ulje semena maline', 'Kokosovo ulje', 'Aloja vera', 'Vitamin E'],
    ingredientsEn: ['Raspberry seed oil', 'Coconut oil', 'Aloe vera', 'Vitamin E'],
    url: 'https://beescare.rs/proizvodi/krema-za-suncanje/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2020/07/Prirodna-krema-za-suncanje-slika.jpg',
    concerns: ['sun protection', 'UV protection', 'sensitive skin sun', 'natural sunscreen'],
    category: 'sun'
  },
  {
    id: 'ulje-suncanje',
    nameSr: 'Ulje za sunčanje',
    nameEn: 'Tanning Oil',
    descriptionSr: 'Prirodni recept za preplanuli ten. Zadržava boju do mesec dana. Miriše na kokos. NEMA SPF — koristiti posle kreme sa faktorom!',
    descriptionEn: 'Natural recipe for a bronzed tan. Maintains color up to a month. Coconut scent. NO SPF — use after sunscreen!',
    ingredients: ['Maslinovo ulje', 'Ulje oraha', 'Ulje semena šargarepe', 'Lavanda', 'Nevena'],
    ingredientsEn: ['Olive oil', 'Walnut oil', 'Carrot seed oil', 'Lavender', 'Calendula'],
    url: 'https://beescare.rs/proizvodi/ulje-za-suncanje/',
    imageUrl: 'https://beescare.rs/wp-content/uploads/2021/08/Ulje-slika-3-1-600x600.jpg',
    concerns: ['tanning', 'bronze tan', 'summer skin'],
    category: 'sun'
  }
]

export type Product = typeof PRODUCTS[0]
